version: '3.11'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    command: bun run dev -- --host 0.0.0.0
    ports:
      - 5173:5173
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose:
      - 5432

volumes:
  postgres_data:
