services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 5001:5001
    depends_on:
      - backend
    volumes:
      - ./static/images/:/var/www/images

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./static/images/:/usr/src/app/images
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level 'debug'
    ports: [8000]
    depends_on:
      - db
    restart: on-failure
    environment:
      - LOG_LEVEL = 'debug'

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev --host 0.0.0.0 --port 5000
    restart: on-failure
    ports: [5000, 5001]
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges

volumes:
  postgres_data:
