services:
  backend:
    build:
      context: ./backend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_IMAGES_URL=${VITE_IMAGES_URL}
    volumes:
      - ./backend:/usr/src/app
      - ./static/images/:/usr/src/app/images
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BODY_SIZE_LIMIT=Infinity

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"

volumes:
  postgres_data:
