version: '3.11'

services:
  nudges:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/dev
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose:
      - 5432

volumes:
  postgres_data:
