version: '3.11'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level 'debug'
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    environment:
      - LOG_LEVEL = 'debug'

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    command: yarn dev --host 0.0.0.0
    restart: on-failure
    ports:
      - 5173:5173
    depends_on:
      - backend
    environment:
      - ORIGIN="http://127.0.0.1"
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose:
      - 5432

volumes:
  postgres_data:
